### ISSUE TITLE
fusion energy output type

### ISSUE THREAD

**Issue by willis936** [Mechaenetia/mechaenetia#1]
Most fusion reactions primarily output heat.  Since this mod has provisions for heat energy, it might make sense to fit that into the balance.  Perhaps this could be used to motivate higher tier reactions (such as hydrogen + B11 that could output electrical power directly).

**Comment by jaskarth** [comment]
I believe you are on the wrong git. This is for Greg's upcoming game, not for GregTech.

**Comment by OvermindDL1** [comment]
Yep, bug reports for GT6 go to:  https://forum.gregtech.overminddl1.com/c/support

:-)

Although GT6 "might" be migrating to Github in short time, depending, could post it there I guess, but for now I'd recommend the forum as he might not fix it after migration unless someone else PR's it.  ^.^

Also, the latest GT6 has fusion reactors, it was 'just' added.  ^.^

**Comment by willis936** [comment]
Whoops
