### ISSUE TITLE
IPA Transcription

### ISSUE THREAD

**Issue by katsu-chan** [Mechaenetia/mechaenetia#16]
Please add IPA transcription of game's name to Readme.md

**Comment by GregoriusT** [comment]
I am quite split on whether or not to add an official pronunciation of the Name, as pretty much any reasonable way to pronounce it seems fine to me, and yes I know there is over a dozen ways to say it out loud, with the way I myself pronounce it being not very english-like.

**Comment by Fyrstikkeske** [comment]
Pls dont end up making it like linux where there are some people saying there is a correct way and a false way. even though there is no correct way since its a community project.
Personally i think its fun when people pronounce project names in weird manners

**Comment by GregoriusT** [comment]
Yeah that is exactly why I did not want to specify a proper way, so people dont end up bickering about it.
