### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by yuesha-yc** [Mechaenetia/mechaenetia#2]
Just want to say cheer

**Comment by GregoriusT** [comment]
Hehe, well technically not the first Issue, if you check the closed ones. I will keep this one open for a bit, maybe people just wanna talk or something, and I did not start properly yet, since I still need to get GT6 done. ^^

**Comment by DanielCordell** [comment]
I left a message on IRC but I don't know if you check that often. Good luck with all this! I hope it goes well 😄 

I just remembered the fact that I'm technically a [moderator of /r/gregtech](https://old.reddit.com/r/GregTech/about/moderators), so if you want the subreddit for this game, I'm happy to give it up to anyone who wants it! If you want this to be distinct from GregTech, maybe a /r/Mechaenetia? Or did you want things to be confined to the forum? Anyway, I'm offering /r/gregtech if you (or anyone else) wants it 😄 

And I'll definitely be making some mods for this when it's ready for it, and maybe any open issues too, depending on how u feel about contributors. It's just the excuse I needed to get gud at Rust.

**Comment by GregoriusT** [comment]
You left a Message on IRC? I pretty much check it almost nonstop when I am awake, so which Channel were you on and as which Username? I am only on #gt-dev on Espernet.

I will put GT6 on GitHub, while keeping it as "my" Project just to supervise it ofcourse. Still learning how to GitHub properly, and I want to finish GT6 before actually putting it out in the wilds of GitHub. ^^

As for Reddit, it's more of a Community Website than an official Site. Just make sure it doesn't turn toxic and it should be fine.

**Comment by DanielCordell** [comment]
Yeah it was on that channel, username 'crdlpls' (as opposed to mr10movie). 

I mean, I'm happy to run a subreddit but I wouldn't know if you'd want to use /r/gregtech or /r/mechaenetia (would using /r/gregtech muddle things? I dunno, up to u really), I just mention cuz I've been a mod for /r/gregtech for 5 years and I'm apparently the only mod left so if anyone wants it for anything I'm game.

**Comment by GregoriusT** [comment]
mechaenetia and gregtech are two different things so dont mix them up. ;)

**Comment by DanielCordell** [comment]
I'm gonna head on IRC then and see if anyone wants to take the subreddit off my hands 😆

**Comment by DOCtorActoAntohich** [comment]
I hope this new game will be cool.

I don't know what else to say. Just do not let your game be like HL3 :)

**Comment by GregoriusT** [comment]
Don't worry, I already confirmed the Game, so I am one step further than Valve. XD

**Comment by GregoriusT** [comment]
Ah so that GitHub Bot works at the very least, nice. Now we just need Greg to stop playing Factorio all the time instead of working and everything is fine.

**Comment by GregoriusT** [comment]
So the Bot also closes Issues 8 days later for some reason. Lets see how long it takes after I reopen it. :D

**Comment by GregoriusT** [comment]
Okay so it is an every 8 days thing. Meanwhile I am sitting here trying to distract myself from the global "flu that shall not be named", because everyone I live with is part of the group of people who could die from it, including myself, though I think my Asthma is not bad enough to have it affect me badly. (and luckily nobody got it yet either). ^^

I will totally not abuse the Bot as a reminder for posting here every now and then. Anyways, back to playing with the Atomic Artillery Mod in Factorio. The best way to use up all your Uranium.

**Comment by justinvvitale** [comment]
hi
